name: Publish the vs code extension
run-name: ${{ github.actor }} is running this GitHub Actions 🚀

on:
  push:
    branches:
    - master
  release:
    types:
    - created

jobs:
  Prepare:
    name: Prepare
    runs-on: node:12-buster
    steps:
      - name: Prepare
        run: |
          npm install @vscode/vsce --save-dev
      - name: Publish
        run: |
          npm run deploy
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
