name: Publish the vs code extension
run-name: ${{ github.actor }} is running this GitHub Actions 🚀

on:
  push:
    branches:
    - master
  release:
    types:
    - created

- name: Publish
  if: startsWith(github.ref, 'refs/tags/')
  run: 
  - npm install @vscode/vsce --save-dev
  - npm run deploy
  env:
    VSCE_PAT: ${{ secrets.VSCE_PAT }}