name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Prepare
        run: npm install @vscode/vsce --save-dev
      - name: build
        run: vsce package
      - name: Publish
        run: npm run deploy
        env:
          VSCE_PAT: ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
